name: Enforce Linting Rules
on: [push, workflow_call]
jobs:
    check-python-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: psf/black@stable
              with:
                  jupyter: true
                  version: "~= 23.0"
